// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TARS_Delivery.Models;

#nullable disable

namespace TARS_Delivery.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240218063517_testMerge")]
    partial class testMerge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TARS_Delivery.Models.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1234 TARS Street",
                            BranchName = "TARS Delivery",
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(297),
                            District = "TARS",
                            PhoneNumber = "123456789",
                            PostalCode = "1234",
                            Province = "TARS",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(314)
                        },
                        new
                        {
                            Id = 2,
                            Address = "1234 TARS Street",
                            BranchName = "TARS Delivery 2",
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(320),
                            District = "TARS",
                            PhoneNumber = "123456789",
                            PostalCode = "1234",
                            Province = "TARS",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(321)
                        },
                        new
                        {
                            Id = 3,
                            Address = "1234 TARS Street",
                            BranchName = "TARS Delivery 3",
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(323),
                            District = "TARS",
                            PhoneNumber = "123456789",
                            PostalCode = "1234",
                            Province = "TARS",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(324)
                        });
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TypeInfo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Số 1, Đường 1, Phường 1, Quận 1, TP HCM",
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(565),
                            District = "Quận 1",
                            Name = "Nguyễn Văn Customer",
                            PhoneNumber = "0123456789",
                            Province = "TP HCM",
                            Status = 1,
                            TypeInfo = 0,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(566),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Số 2, Đường 2, Phường 2, Quận 2, TP HCM",
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(571),
                            District = "Quận 2",
                            Name = "Trần Thị Customer",
                            PhoneNumber = "0987654321",
                            Province = "TP HCM",
                            Status = 1,
                            TypeInfo = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(571),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "Số 3, Đường 3, Phường 3, Quận 3, TP HCM",
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(609),
                            District = "Quận 3",
                            Name = "Lê Văn Customer",
                            PhoneNumber = "044333333",
                            Province = "TP HCM",
                            Status = 1,
                            TypeInfo = 0,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(610),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubmitedInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Số 1, Đường 1, Phường 1, Quận 1, TP HCM",
                            Avatar = "avatar.jpg",
                            BranchId = 1,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(651),
                            District = "Quận 1",
                            Email = "emp1@emp1",
                            EmployeeCode = "EMP001",
                            Fullname = "Nguyễn Văn Employee",
                            Password = "123",
                            PhoneNumber = "0123456789",
                            Province = "TP HCM",
                            RoleId = 1,
                            Status = 1,
                            SubmitedInfo = "SubmitedInfo",
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(652)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Số 2, Đường 2, Phường 2, Quận 2, TP HCM",
                            Avatar = "avatar.jpg",
                            BranchId = 2,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(657),
                            District = "Quận 2",
                            Email = "emp2@emp2",
                            EmployeeCode = "EMP002",
                            Fullname = "Trần Thị Employee",
                            Password = "123",
                            PhoneNumber = "0987654321",
                            Province = "TP HCM",
                            RoleId = 2,
                            Status = 1,
                            SubmitedInfo = "SubmitedInfo",
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(658)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Số 3, Đường 3, Phường 3, Quận 3, TP HCM",
                            Avatar = "avatar.jpg",
                            BranchId = 3,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(664),
                            District = "Quận 3",
                            Email = "emp3@emp3",
                            EmployeeCode = "EMP003",
                            Fullname = "Lê Văn Employee",
                            Password = "123",
                            PhoneNumber = "12548897451",
                            Province = "TP HCM",
                            RoleId = 3,
                            Status = 1,
                            SubmitedInfo = "SubmitedInfo",
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(665)
                        });
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.FeeCustom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Distance")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("FeeCharge")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("LocationIdFrom")
                        .HasColumnType("int");

                    b.Property<int>("LocationIdTo")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TimeProcess")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationIdFrom");

                    b.HasIndex("LocationIdTo");

                    b.HasIndex("ServiceId");

                    b.ToTable("FeeCustoms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(711),
                            Distance = 15.5m,
                            FeeCharge = 35000.00m,
                            LocationIdFrom = 1,
                            LocationIdTo = 3,
                            ServiceId = 1,
                            Status = 1,
                            TimeProcess = 48,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(712)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(716),
                            Distance = 25.0m,
                            FeeCharge = 45000.00m,
                            LocationIdFrom = 1,
                            LocationIdTo = 8,
                            ServiceId = 2,
                            Status = 1,
                            TimeProcess = 72,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(717)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(721),
                            Distance = 5.0m,
                            FeeCharge = 25000.00m,
                            LocationIdFrom = 1,
                            LocationIdTo = 2,
                            ServiceId = 3,
                            Status = 1,
                            TimeProcess = 24,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(722)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(726),
                            Distance = 10.0m,
                            FeeCharge = 20000.00m,
                            LocationIdFrom = 1,
                            LocationIdTo = 1,
                            ServiceId = 1,
                            Status = 1,
                            TimeProcess = 24,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(727)
                        });
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.GeneralSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GeneralSettings");
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.HistoryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeIdNextStep")
                        .HasColumnType("int");

                    b.Property<string>("HistoryNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("Photos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessStep")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Step")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeIdNextStep");

                    b.HasIndex("PackageId");

                    b.ToTable("HistoryLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(777),
                            EmployeeId = 1,
                            EmployeeIdNextStep = 2,
                            HistoryNote = "Đang chờ lấy hàng",
                            PackageId = 1,
                            Photos = "https://tars.com/photos/1",
                            ProcessStep = 0,
                            Status = 1,
                            Step = 0,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(779)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(783),
                            EmployeeId = 2,
                            EmployeeIdNextStep = 3,
                            HistoryNote = "Đang chờ lấy hàng",
                            PackageId = 2,
                            Photos = "https://tars.com/photos/2",
                            ProcessStep = 0,
                            Status = 1,
                            Step = 0,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(784)
                        });
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<decimal>("ItemValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemWeight")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(836),
                            ItemName = "Quần áo",
                            ItemQuantity = 5,
                            ItemType = 0,
                            ItemValue = 1000000m,
                            ItemWeight = 2,
                            PackageId = 1,
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(837)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(842),
                            ItemName = "Giày dép",
                            ItemQuantity = 3,
                            ItemType = 1,
                            ItemValue = 500000m,
                            ItemWeight = 1,
                            PackageId = 2,
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(843)
                        });
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationLevel")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationOf")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationOf");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(894),
                            LocationLevel = 0,
                            LocationName = "TP HCM",
                            PostalCode = "700000",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(895)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(900),
                            LocationLevel = 1,
                            LocationName = "Quận 1",
                            LocationOf = 1,
                            PostalCode = "710100",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(900)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(904),
                            LocationLevel = 1,
                            LocationName = "Quận 2",
                            LocationOf = 1,
                            PostalCode = "713000",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(905)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(909),
                            LocationLevel = 1,
                            LocationName = "Quận 3",
                            LocationOf = 1,
                            PostalCode = "722000",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(910)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(913),
                            LocationLevel = 1,
                            LocationName = "Quận 4",
                            LocationOf = 1,
                            PostalCode = "754000",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(914)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(918),
                            LocationLevel = 1,
                            LocationName = "Quận 5",
                            LocationOf = 1,
                            PostalCode = "748000",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(918)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(922),
                            LocationLevel = 1,
                            LocationName = "Quận 6",
                            LocationOf = 1,
                            PostalCode = "746000",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(922)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(926),
                            LocationLevel = 1,
                            LocationName = "Quận 7",
                            LocationOf = 1,
                            PostalCode = "756000",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(927)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(930),
                            LocationLevel = 1,
                            LocationName = "Quận 8",
                            LocationOf = 1,
                            PostalCode = "751500",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(931)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(934),
                            LocationLevel = 1,
                            LocationName = "Quận 9",
                            LocationOf = 1,
                            PostalCode = "715000",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(935)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(938),
                            LocationLevel = 1,
                            LocationName = "Quận 10",
                            LocationOf = 1,
                            PostalCode = "740010",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(939)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(942),
                            LocationLevel = 1,
                            LocationName = "Quận 11",
                            LocationOf = 1,
                            PostalCode = "743800",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(943)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(946),
                            LocationLevel = 1,
                            LocationName = "Quận 12",
                            LocationOf = 1,
                            PostalCode = "729400",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(947)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(950),
                            LocationLevel = 1,
                            LocationName = "Quận Gò Vấp",
                            LocationOf = 1,
                            PostalCode = "727010",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(951)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(954),
                            LocationLevel = 1,
                            LocationName = "Quận Tân Bình",
                            LocationOf = 1,
                            PostalCode = "736090",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(955)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(958),
                            LocationLevel = 1,
                            LocationName = "Quận Tân Phú",
                            LocationOf = 1,
                            PostalCode = "760000",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(959)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(962),
                            LocationLevel = 1,
                            LocationName = "Quận Phú Nhuận",
                            LocationOf = 1,
                            PostalCode = "725060",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(962)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(966),
                            LocationLevel = 1,
                            LocationName = "Quận Bình Thạnh",
                            LocationOf = 1,
                            PostalCode = "718440",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(966)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(970),
                            LocationLevel = 1,
                            LocationName = "Quận Thủ Đức",
                            LocationOf = 1,
                            PostalCode = "720150",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(971)
                        });
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCodeFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCodeTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Step")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TrackingCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressFrom = "Số 1, Đường 1, Phường 1, Quận 1, TP HCM",
                            AddressTo = "Số 2, Đường 2, Phường 2, Quận 2, TP HCM",
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(1034),
                            NameFrom = "Nguyễn Văn A",
                            NameTo = "Trần Thị B",
                            PackageNote = "Giao hàng cẩn thận",
                            Photos = "photo1.jpg",
                            PostalCodeFrom = "700000",
                            PostalCodeTo = "700000",
                            ServiceId = 1,
                            Status = 1,
                            Step = 1,
                            TotalFee = 100000m,
                            TrackingCode = "123456789",
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(1034),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddressFrom = "Số 2, Đường 2, Phường 2, Quận 2, TP HCM",
                            AddressTo = "Số 3, Đường 3, Phường 3, Quận 3, TP HCM",
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(1040),
                            NameFrom = "Trần Thị B",
                            NameTo = "Lê Văn C",
                            PackageNote = "Giao hàng cẩn thận",
                            Photos = "photo2.jpg",
                            PostalCodeFrom = "700000",
                            PostalCodeTo = "700000",
                            ServiceId = 1,
                            Status = 1,
                            Step = 1,
                            TotalFee = 100000m,
                            TrackingCode = "987654321",
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(1041),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            PermissionName = "User"
                        });
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Warehouse",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "Delivery",
                            Status = 0
                        });
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.RoleHasPermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId1")
                        .HasColumnType("int");

                    b.Property<int>("RoleId2")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId1");

                    b.ToTable("RoleHasPermissions");
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeighFrom")
                        .HasColumnType("int");

                    b.Property<int>("WeighTo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(1269),
                            ServiceDescription = "Fast and secure international delivery service",
                            ServiceName = "EMS Delivery Service",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(1270),
                            WeighFrom = 0,
                            WeighTo = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(1274),
                            ServiceDescription = "Reliable freight and cargo delivery solutions",
                            ServiceName = "Freight Delivery Services",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(1275),
                            WeighFrom = 0,
                            WeighTo = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(1278),
                            ServiceDescription = "Fast and convenient express delivery service",
                            ServiceName = "Express Delivery",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(1279),
                            WeighFrom = 0,
                            WeighTo = 0
                        });
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasFilter("[Phone] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "avatar.jpg",
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(1152),
                            Email = "usera@usera",
                            Fullname = "Nguyễn Văn User",
                            Password = "123",
                            Phone = "0123456789",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(1153)
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "avatar.jpg",
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(1223),
                            Email = "userb@userb",
                            Fullname = "Trần Thị User",
                            Password = "123",
                            Phone = "0987654321",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(1224)
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "avatar.jpg",
                            CreatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(1228),
                            Email = "userc@userc",
                            Fullname = "Lê Văn User",
                            Password = "123",
                            Phone = "023023920392",
                            Status = 1,
                            UpdatedAt = new DateTime(2024, 2, 18, 13, 35, 17, 156, DateTimeKind.Local).AddTicks(1228)
                        });
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.Customer", b =>
                {
                    b.HasOne("TARS_Delivery.Models.Entities.User", "User")
                        .WithMany("Customers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.Employee", b =>
                {
                    b.HasOne("TARS_Delivery.Models.Entities.Branch", "Branch")
                        .WithMany("Employees")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TARS_Delivery.Models.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.FeeCustom", b =>
                {
                    b.HasOne("TARS_Delivery.Models.Entities.Location", "LocationFrom")
                        .WithMany()
                        .HasForeignKey("LocationIdFrom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TARS_Delivery.Models.Entities.Location", "LocationTo")
                        .WithMany()
                        .HasForeignKey("LocationIdTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TARS_Delivery.Models.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocationFrom");

                    b.Navigation("LocationTo");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.HistoryLog", b =>
                {
                    b.HasOne("TARS_Delivery.Models.Entities.Employee", "Employee")
                        .WithMany("HistoryLogs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TARS_Delivery.Models.Entities.Employee", "EmployeeNextStep")
                        .WithMany()
                        .HasForeignKey("EmployeeIdNextStep");

                    b.HasOne("TARS_Delivery.Models.Entities.Package", "Package")
                        .WithMany("HistoryLogs")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("EmployeeNextStep");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.Item", b =>
                {
                    b.HasOne("TARS_Delivery.Models.Entities.Package", "Package")
                        .WithMany("Items")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.Location", b =>
                {
                    b.HasOne("TARS_Delivery.Models.Entities.Location", "ParentLocation")
                        .WithMany("ChildLocations")
                        .HasForeignKey("LocationOf")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.Package", b =>
                {
                    b.HasOne("TARS_Delivery.Models.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TARS_Delivery.Models.Entities.User", "User")
                        .WithMany("Packages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.RoleHasPermission", b =>
                {
                    b.HasOne("TARS_Delivery.Models.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TARS_Delivery.Models.Entities.Role", null)
                        .WithMany("RoleHasPermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TARS_Delivery.Models.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.Branch", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.Employee", b =>
                {
                    b.Navigation("HistoryLogs");
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.Location", b =>
                {
                    b.Navigation("ChildLocations");
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.Package", b =>
                {
                    b.Navigation("HistoryLogs");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.Role", b =>
                {
                    b.Navigation("RoleHasPermissions");
                });

            modelBuilder.Entity("TARS_Delivery.Models.Entities.User", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
