using Microsoft.EntityFrameworkCore;
using TARS_Delivery.Models.Entities;
using TARS_Delivery.Models.Enums;

namespace TARS_Delivery.Seeders
{
    public class PackageSeeders
    {
        public PackageSeeders(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Package>().HasData(
                new Package
                {
                    Id = 1,
                    TrackingCode = "1",
                    NameFrom = "Nguyễn Văn A",
                    AddressFrom = "Số 1, Đường 1, Phường 1, Quận 1, TP HCM",
                    PostalCodeFrom = "700000",
                    PhoneFrom = "0123456789",
                    NameTo = "Trần Thị B",
                    AddressTo = "Số 2, Đường 2, Phường 2, Quận 2, TP HCM",
                    PhoneTo = "0123456789",
                    PostalCodeTo = "700000",
                    PackageNote = "Giao hàng cẩn thận",
                    TotalFee = 100000,
                    FeeCustomId = 1,
                    PackageType = EItemType.Document,
                    TimeProcess = 18,
                    UserId = 1,
                    Step = EPackageStatus.WaitingForPickup,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now,
                    Status = EStatusData.Active
                },
                new Package
                {
                    Id = 2,
                    TrackingCode = "2",
                    NameFrom = "Trần Thị B",
                    AddressFrom = "Số 2, Đường 2, Phường 2, Quận 2, TP HCM",
                    PhoneFrom = "0123456789",
                    PostalCodeFrom = "700000",
                    NameTo = "Lê Văn C",
                    AddressTo = "Số 3, Đường 3, Phường 3, Quận 3, TP HCM",
                    PhoneTo = "0123456789",
                    PostalCodeTo = "700000",
                    PackageNote = "Giao hàng cẩn thận",
                    TotalFee = 100000,
                    PackageType = EItemType.Pack,
                    TimeProcess = 30,
                    FeeCustomId = 1,
                    UserId = 2,
                    Step = EPackageStatus.WaitingForPickup,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now,
                    Status = EStatusData.Active
                },
                new Package
                {
                    Id = 3,
                    TrackingCode = "3",
                    NameFrom = "Trần Thị B",
                    AddressFrom = "Số 2, Đường 2, Phường 2, Quận 2, TP HCM",
                    PhoneFrom = "1212",
                    PostalCodeFrom = "700000",
                    NameTo = "Lê Văn C",
                    AddressTo = "Số 3, Đường 3, Phường 3, Quận 3, TP HCM",
                    PhoneTo = "0123456789",
                    PostalCodeTo = "700000",
                    PackageNote = "Giao hàng cẩn thận",
                    TotalFee = 100000,
                    PackageType = EItemType.Pack,
                    TimeProcess = 30,
                    FeeCustomId = 1,
                    UserId = 2,
                    Step = EPackageStatus.Created,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now,
                    Status = EStatusData.Active
                },
                new Package
                {
                    Id = 4,
                    TrackingCode = "4",
                    NameFrom = "Trần Thị B",
                    AddressFrom = "Số 2, Đường 2, Phường 2, Quận 2, TP HCM",
                    PhoneFrom = "1313",
                    PostalCodeFrom = "700000",
                    NameTo = "Lê Văn C",
                    AddressTo = "Số 3, Đường 3, Phường 3, Quận 3, TP HCM",
                    PhoneTo = "0123456789",
                    PostalCodeTo = "700000",
                    PackageNote = "Giao hàng cẩn thận",
                    TotalFee = 100000,
                    PackageType = EItemType.Pack,
                    TimeProcess = 30,
                    FeeCustomId = 1,
                    UserId = 2,
                    Step = EPackageStatus.WarehouseFrom,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now,
                    Status = EStatusData.Active
                },
                new Package
                {
                    Id = 5,
                    TrackingCode = "5",
                    NameFrom = "Trần Thị B",
                    AddressFrom = "Số 2, Đường 2, Phường 2, Quận 2, TP HCM",
                    PhoneFrom = "1414",
                    PostalCodeFrom = "700000",
                    NameTo = "Lê Văn C",
                    AddressTo = "Số 3, Đường 3, Phường 3, Quận 3, TP HCM",
                    PhoneTo = "0123456789",
                    PostalCodeTo = "700000",
                    PackageNote = "Giao hàng cẩn thận",
                    TotalFee = 100000,
                    PackageType = EItemType.Pack,
                    TimeProcess = 30,
                    FeeCustomId = 1,
                    UserId = 2,
                    Step = EPackageStatus.InTransit,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now,
                    Status = EStatusData.Active
                },
                new Package
                {
                    Id = 6,
                    TrackingCode = "6",
                    NameFrom = "Trần Thị B",
                    AddressFrom = "Số 2, Đường 2, Phường 2, Quận 2, TP HCM",
                    PhoneFrom = "1515",
                    PostalCodeFrom = "700000",
                    NameTo = "Lê Văn C",
                    AddressTo = "Số 3, Đường 3, Phường 3, Quận 3, TP HCM",
                    PhoneTo = "0123456789",
                    PostalCodeTo = "700000",
                    PackageNote = "Giao hàng cẩn thận",
                    TotalFee = 100000,
                    PackageType = EItemType.Pack,
                    TimeProcess = 30,
                    FeeCustomId = 1,
                    UserId = 2,
                    Step = EPackageStatus.WarehouseTo,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now,
                    Status = EStatusData.Active
                },
                new Package
                {
                    Id = 7,
                    TrackingCode = "7",
                    NameFrom = "Trần Thị B",
                    AddressFrom = "Số 2, Đường 2, Phường 2, Quận 2, TP HCM",
                    PhoneFrom = "1616",
                    PostalCodeFrom = "700000",
                    NameTo = "Lê Văn C",
                    AddressTo = "Số 3, Đường 3, Phường 3, Quận 3, TP HCM",
                    PhoneTo = "0123456789",
                    PostalCodeTo = "700000",
                    PackageNote = "Giao hàng cẩn thận",
                    TotalFee = 100000,
                    PackageType = EItemType.Pack,
                    TimeProcess = 30,
                    FeeCustomId = 1,
                    UserId = 2,
                    Step = EPackageStatus.Shipping,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now,
                    Status = EStatusData.Active
                },
                new Package
                {
                    Id = 8,
                    TrackingCode = "8",
                    NameFrom = "Trần Thị B",
                    AddressFrom = "Số 2, Đường 2, Phường 2, Quận 2, TP HCM",
                    PhoneFrom = "1717",
                    PostalCodeFrom = "700000",
                    NameTo = "Lê Văn C",
                    AddressTo = "Số 3, Đường 3, Phường 3, Quận 3, TP HCM",
                    PhoneTo = "0123456789",
                    PostalCodeTo = "700000",
                    PackageNote = "Giao hàng cẩn thận",
                    TotalFee = 100000,
                    PackageType = EItemType.Pack,
                    TimeProcess = 30,
                    FeeCustomId = 1,
                    UserId = 2,
                    Step = EPackageStatus.Delivered,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now,
                    Status = EStatusData.Active
                },
                new Package
                {
                    Id = 9,
                    TrackingCode = "9",
                    NameFrom = "Trần Thị B",
                    AddressFrom = "Số 2, Đường 2, Phường 2, Quận 2, TP HCM",
                    PhoneFrom = "1919",
                    PostalCodeFrom = "700000",
                    NameTo = "Lê Văn C",
                    AddressTo = "Số 3, Đường 3, Phường 3, Quận 3, TP HCM",
                    PhoneTo = "0123456789",
                    PostalCodeTo = "700000",
                    PackageNote = "Giao hàng cẩn thận",
                    TotalFee = 100000,
                    PackageType = EItemType.Pack,
                    TimeProcess = 30,
                    FeeCustomId = 1,
                    UserId = 2,
                    Step = EPackageStatus.Cancelled,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now,
                    Status = EStatusData.Active
                },
                new Package
                {
                    Id = 10,
                    TrackingCode = "10",
                    NameFrom = "Trần Thị B",
                    AddressFrom = "Số 2, Đường 2, Phường 2, Quận 2, TP HCM",
                    PhoneFrom = "2020",
                    PostalCodeFrom = "700000",
                    NameTo = "Lê Văn C",
                    AddressTo = "Số 3, Đường 3, Phường 3, Quận 3, TP HCM",
                    PhoneTo = "0123456789",
                    PostalCodeTo = "700000",
                    PackageNote = "Giao hàng cẩn thận",
                    TotalFee = 100000,
                    PackageType = EItemType.Pack,
                    TimeProcess = 30,
                    FeeCustomId = 1,
                    UserId = 2,
                    Step = EPackageStatus.Returned,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now,
                    Status = EStatusData.Active
                },
                new Package
                {
                    Id = 11,
                    TrackingCode = "11",
                    NameFrom = "Trần Thị B",
                    AddressFrom = "Số 2, Đường 2, Phường 2, Quận 2, TP HCM",
                    PhoneFrom = "2020",
                    PostalCodeFrom = "700000",
                    NameTo = "Lê Văn C",
                    AddressTo = "Số 3, Đường 3, Phường 3, Quận 3, TP HCM",
                    PhoneTo = "0123456789",
                    PostalCodeTo = "700000",
                    PackageNote = "Giao hàng cẩn thận",
                    TotalFee = 100000,
                    PackageType = EItemType.Pack,
                    TimeProcess = 30,
                    FeeCustomId = 1,
                    UserId = 2,
                    Step = EPackageStatus.Lost,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now,
                    Status = EStatusData.Active
                }
            );
        }
    }
}